package Client;

import addon.MyDate;
 /**
 *
 * @author damie
 */
public class ClientInterface extends javax.swing.JFrame {
    String IDClient;
    static ClientBack bc;
    static String address = "127.0.0.1";
    static int port = 1201;
    
    static boolean closeConnexion = false;
    
    static String splitCharacter = "\\|";
    
    MyDate minDate = new MyDate(1,1,1,1,1,1);
    
    public ClientInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayMsg = new javax.swing.JTextArea();
        IDField = new javax.swing.JTextField();
        ConnectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        DisplayMsg.setColumns(20);
        DisplayMsg.setRows(5);
        jScrollPane1.setViewportView(DisplayMsg);
        DisplayMsg.getAccessibleContext().setAccessibleName("");

        IDField.setText("DefaultID\n");

        ConnectButton.setText("Connect");
        ConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConnectButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sendButton)
                                .addGap(0, 202, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConnectButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //hit button send
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String msgText;  
        msgText = (jTextField1.getText()).trim();
        DataMessage msg = new DataMessage(IDClient, 1, MyDate.now(), msgText);
        bc.sendMsg(msg);
        DisplayMsg.setText(DisplayMsg.getText() + "\n\t" + IDClient + " : " + msgText);
        jTextField1.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    //hit button connect, will disappear
    private void ConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectButtonActionPerformed
        try {
            IDClient = IDField.getText().trim();
            bc.setIDClient(IDClient);
            bc.loadMessages(1,minDate);
            System.out.println("ID set");
        } catch (Exception e) {}
        
    }//GEN-LAST:event_ConnectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {  
            @Override
            public void run() {  
            new ClientInterface().setVisible(true);  
            }  
        });  
        try{
            bc = new ClientBack(address, port);
            String msgIn = "";
            while (!closeConnexion) { 
                System.out.println("attente de la reponse");
                String responses = bc.read();
                System.out.println("reception de la reponse");
                InterpretResponse(responses);
            }
        } catch (Exception e) {}
    }
    
    //same as server side
    private static void InterpretResponse(String responses){
    	String[] responsesA = responses.split("\\|");
        for (String response : responsesA) {
			String[] responseA = response.split("@", 2);
			switch (responseA[0]) {
			case "msg":
				System.out.println("interpret as msg");
				DataMessage msg = TranslateToMsg(responseA[1]);
				System.out.println("translate done");
				PrintNewMessage(msg);
				break;

			case "join":
				System.out.println("interpret as join");
				PrintLogin(responseA[1]);
				break;

			case "close":
				closeConnexion = true;
				break;

			default:
			}
		}
    }
    
    //print message in the textbox
    public static void PrintNewMessage(DataMessage msg){
        System.out.println("affichage du msg");
        DisplayMsg.setText(DisplayMsg.getText().trim() + "\n " + msg.ToPrint());
    }
    
    public static void PrintLogin(String id){
        System.out.println("affichage du login");
        DisplayMsg.setText(DisplayMsg.getText().trim() + "\n " + id + " join.");
    }
    
    private static DataMessage TranslateToMsg(String responce){
    	System.out.println(responce);
        String[] data = responce.split("@",4);
        MyDate date = new MyDate(data[2]);
        return new DataMessage(data[0], Integer.parseInt(data[1]), date, data[3]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectButton;
    private static javax.swing.JTextArea DisplayMsg;
    private javax.swing.JTextField IDField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
